### ISSUE TITLE
It does not work on Windows

### ISSUE THREAD

**Issue by sdimitrijevic** [bluegray/lein-scss#2]
Running lein-scss on Windows results in the following exception:

> java.util.regex.PatternSyntaxException: illegal/unsupported escape sequence near index 4
> “C:\Users\XXX\git\project\src\scss”
> at java.util.regex.Pattern.error  <Pattern.java:1955>
> …

The error occurs when getting the absolute path of a file. The cause is the use of backslashes as path separators on Windows.

**Comment by bluegray** [comment]
I'm not sure how many windows lein users there are, but I'll be happy to accept any PRs for windows support ;)

**Comment by nmikhail1** [comment]
I am using lein-scss in a project that needs to run on Linux/Mac/Windows.
lein-scss works fine on Linux and Mac. For Windows I use cygwin so that the same Linux scripts can be used.
When lein-scss is called, I get the same error sdimitrijevic has reported above.
Since clojure runs on JVM it uses Java to handle files resulting in the backslash being used for the absolute path even if the whole process has been launched from cygwin

By debugging the code I found that the issue happens on line 34 in scss.clj

(string/replace (re-pattern (str "^" source)) "")

source contains the file name with backslash. Calling re-pattern will generate the above error since backslash is a metachar for regex.
I was able to solve the issue by escaping the source variable before calling re-pattern (i.e. making sure any regex special char have been escaped)

(import 'java.util.regex.Pattern)
...
(string/replace (re-pattern (str "^" **(Pattern/quote source)**)) "")

I would appreciate if you can adjust the code accordingly and provide a new version that fixes the issue
